"""Added Event class

Revision ID: c8f9a156c93f
Revises: feb84e35c08c
Create Date: 2025-08-06 18:48:02.120236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8f9a156c93f'
down_revision = 'feb84e35c08c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=30), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('seats_left', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_title'), ['title'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_title'))
        batch_op.drop_index(batch_op.f('ix_event_description'))

    op.drop_table('event')
    # ### end Alembic commands ###
